[webodm]
url = "https://webodm.rettungsrobotik.de"
project = "CREXDATA Trials"

[kafka]
url = "server.crexdata.eu:9092" # localhost:9092 when testing with local cluster
topic = "UPB-CREXDATA-RealtimeDEM-Stream"
key = "dsm.tif"

# If the server does not use authentication, remove this block.
[kafka.auth]
cert_dir = "config" # use absolute path, or relative to cwd
ca = "kafka_ca.crt"
client_crt = "kafka_client.crt"
client_key = "kafka_client.key"
