[webodm]
url = "https://webodm.rettungsrobotik.de"
project = "CREXDATA Trials"

[kafka]
url = "server.crexdata.eu:9092" # localhost:9092 when testing with local cluster
topic = "UPB-CREXDATA-RealtimeDEM-Stream"
key = "dsm.tif"

[kafka.ssl]
ca_location = "config/kafka_ca.crt"
certificate_location = "config/kafka_client.crt"
key_location = "config/kafka_client.key"
